# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLOhtX64T77k6LiiTqrX3Ca6IL4ssVhk
"""

pip install streamlit

import streamlit as st
import pandas as pd
import tensorflow as tf
import pickle

# Cargar modelo y herramientas
model = tf.keras.models.load_model("modelo_riesgo_microbiologico.h5")
scaler = pickle.load(open("scaler.pkl", "rb"))
columnas = pickle.load(open("columnas.pkl", "rb"))

# Título
st.title("🧪 Predicción de Riesgo Microbiológico en Alimentos")

# Inputs del usuario
ph = st.number_input("pH", 2.0, 7.0, step=0.1)
aw = st.number_input("Actividad de agua (aw)", 0.5, 1.0, step=0.01)
grasa = st.number_input("Grasa (%)", 0.0, 100.0, step=0.1)
conservante = st.selectbox("Conservante", ["Ninguno", "Sorbato", "Benzoato"])
proceso = st.selectbox("Proceso térmico", ["Crudo", "Pasteurizado", "UHT"])

if st.button("🔍 Predecir riesgo"):
    # Preprocesar input
    df = pd.DataFrame({
        'pH': [ph],
        'aw': [aw],
        'Grasa': [grasa],
        'Conservante': [conservante],
        'Proceso': [proceso]
    })

    df_encoded = pd.get_dummies(df)
    for col in columnas:
        if col not in df_encoded.columns:
            df_encoded[col] = 0
    df_encoded = df_encoded[columnas]

    df_scaled = scaler.transform(df_encoded)

    # Predicción
    pred = model.predict(df_scaled)[0][0]
    riesgo = "ALTO" if pred > 0.5 else "BAJO"

    st.success(f"✅ Riesgo estimado: {riesgo} ({pred:.2f})")